FROM golang:latest AS build-env

WORKDIR /go/src/app

ADD . /go/src/app

RUN go get -u -v github.com/kardianos/govendor \
&& govendor sync \
&& GOOS=linux GOARCH=386 go build -v -o /go/src/app/app-server

FROM scratch

COPY --from=build-env /go/src/app/app-server . 

EXPOSE 8080

CMD ["./app-server"]


